//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLLAgroFlor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class registro
    {
        [ScaffoldColumn(false)]
        public int id { get; set; }


        public int variedad_id { get; set; }
        public int floricola_id { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        [Display(Name = "Fecha de publicación")]
        public Nullable<System.DateTime> fecha { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Tallos requeridos"), MaxLength(150)]
        [Display(Name = "Bonches medida")]
        public string bonche_med { get; set; }

        [DataType(DataType.Duration)]
        [Range(5, 150, ErrorMessage = "Ingrese un precio correcto")]
        [Display(Name = "Precio tallo exportación")]
        public Nullable<double> precio_tall_exp { get; set; }

        [DataType(DataType.Duration)]
        [Range(0, 10000, ErrorMessage = "Ingresa un número valido")]
        [Display(Name = "Tallos de nacional")]
        public Nullable<int> tall_nacional { get; set; }

        [DataType(DataType.Duration)]
        [Range(0, 10000, ErrorMessage = "Ingresa un número valido")]
        [Display(Name = "Tallos totales")]
        public Nullable<int> total_tallos { get; set; }

        [DataType(DataType.Duration)]
        [Range(5, 150, ErrorMessage = "Ingrese un precio correcto")]
        [Display(Name = "Precio por bonche")]
        public Nullable<double> precio_nac { get; set; }
    
        public virtual floricola floricola { get; set; }

        public virtual variedades variedades { get; set; }

    }
}
